/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/zXc7pd0lVrK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"

export function ChangeLog() {
  return (
    <div className="bg-white text-gray-900 min-h-screen p-8">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-3xl font-bold">Changelog</h1>
        <p className="text-xs italic text-gray-500">Inspired by Linear</p>
        <p className="text-gray-600 mt-1">New updates and improvements to Linear.</p>
        <div className="flex gap-4 mt-2 text-blue-500">
          <a className="underline" href="#">
            Subscribe to updates
          </a>
          <a className="underline" href="#">
            Follow us on Twitter
          </a>
        </div>
        <div className="mt-8 grid grid-cols-[100px_1fr] items-start gap-4">
          <div className="space-y-2">
            <h2 className="text-md font-semibold">April 3, 2024</h2>
          </div>
          <div>
            <h3 className="text-xl font-semibold">Swimlanes</h3>
            <img
              alt="Swimlanes feature illustration"
              className="mt-4"
              height="432"
              src="/placeholder.svg"
              style={{
                aspectRatio: "768/432",
                objectFit: "cover",
              }}
              width="768"
            />
            <p className="mt-4">
              Swimlanes bring a powerful new way to visualize your projects and issues on the board view. This highly
              requested feature allows you to group cards into rows based on different dimensions and instantly see how
              work is distributed across teams, projects, assignees, and other properties.
            </p>
            <ul className="list-disc ml-6 mt-2">
              <li>View a high-level overview of the roadmap by quarter or team</li>
              <li>Use simple drag-and-drop to reorganize, reassign, or update issues</li>
              <li>Understand resource allocation across members of your team</li>
              <li>Review work per project or assignee during a stand-up</li>
            </ul>
          </div>
          <div className="space-y-2">
            <h2 className="text-md font-semibold">March 27, 2024</h2>
          </div>
        </div>
      </div>
    </div>
  )
}
