"use client";

/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Ixydi5jz06w
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import React, { useEffect, useState } from 'react';
import { Job, ApplyOption } from '@prisma/client';
import { toast } from 'sonner';
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { HoverCardTrigger, HoverCardContent, HoverCard } from "@/components/ui/hover-card"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { QueryFunctionContext, useInfiniteQuery } from '@tanstack/react-query'
import { Skeleton } from "@/components/ui/skeleton"
import { debounce } from "lodash";
import { JSX, SVGProps } from "react"
import axios from 'axios';
import {
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton,
} from "@clerk/nextjs";
import TruncatedText from './truncated-text';
import Bookmark from './bookmark';
import { JobSearchInfoCard } from './info-card';
import { UrlObject } from 'url';
import EmailFrequencySelector from './email-frequency-selector';

const fetchJobs = async ({ pageParam = 0, queryKey }: QueryFunctionContext): Promise<any> => {
  // Assert the structure of queryKey to match our expected type
  const [searchTerm, location] = queryKey[1] as [string, string];
  const params = new URLSearchParams({
    search: searchTerm,
    location: location,
    page: String(Number(pageParam) + 1),
    pageSize: '10'
  }).toString();
  const response = await axios.get(`/api/jobs?${params}`);
  return response.data;
};


export function JobBoard() {
  const [jobs, setJobs] = useState([] as Job[]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [location, setLocation] = useState('');
  const loadMoreRef = React.useRef(null);

  const {
    data,
    fetchNextPage,
    hasNextPage,
    isFetchingNextPage,
    isFetching,
  } = useInfiniteQuery({
    queryKey: ['jobs', [searchTerm, location]],
    queryFn: fetchJobs,
    getNextPageParam: (lastPage, allPages) => {
      const morePagesExist = lastPage?.jobs?.length === 10;
      if (!morePagesExist) return undefined;
      return allPages.length;
    },
    initialPageParam: 0,
  });

  const handleSearchChange = (e: { target: { value: React.SetStateAction<string>; }; }) => setSearchTerm(e.target.value);
  const handleLocationChange = (value: React.SetStateAction<string>) => setLocation(value);

  const renderSkeleton = () => (
    <div className="flex flex-col space-y-3">
      {[...Array(5)].map((_, index) => (
        <Skeleton key={index} className="h-24 w-full rounded-md" />
      ))}
    </div>
  );

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        const first = entries[0];
        if (first.isIntersecting && hasNextPage) {
          fetchNextPage();
        } else if (first.isIntersecting && !hasNextPage && (data?.pages.length ?? 0) > 0) {
          toast.info('No more jobs to load!');
        }
      },
      { threshold: 0.1 }
    );

    const currentRef = loadMoreRef.current;
    if (currentRef) {
      observer.observe(currentRef);
    }

    return () => {
      if (currentRef) {
        observer.unobserve(currentRef);
      }
    };
  }, [fetchNextPage, hasNextPage, data]);

  return (
    <div className="flex flex-col min-h-screen bg-white dark:bg-gray-900">
      <header className="container px-4 md:px-6 py-4 flex items-center gap-4">
        <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
          Home
        </Link>
        <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
          About
        </Link>
        <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
          Contact
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="https://github.com/" className="flex items-center gap-2" target="_blank" rel="noopener noreferrer">
            <GithubIcon className="w-6 h-6" />
          </Link>

          <EmailFrequencySelector />

          <SignedIn>
            <UserButton />
          </SignedIn>
          <SignedOut>
            <SignInButton />
          </SignedOut>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 md:gap-8">
              <div className="flex flex-col md:flex-row items-start md:items-center gap-4 md:gap-8">
                <div className="grid gap-1">
                  <h1 className="text-2xl font-bold tracking-tight">Job Listings</h1>
                  <p className="text-gray-500 dark:text-gray-400">
                    Explore the latest job postings from top tech companies.
                  </p>
                </div>
                <div className="flex gap-4 md:gap-6 md:ml-auto">
                  <Input className="w-full md:w-64" placeholder="Search jobs..." type="search" value={searchTerm} onChange={handleSearchChange} />
                  <Select onValueChange={(value) => handleLocationChange(value)} >
                    <SelectTrigger className="w-32">
                      <SelectValue placeholder="Location" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="New York">New York</SelectItem>
                      <SelectItem value="New Jersey">New Jersey</SelectItem>
                    </SelectContent>
                  </Select>
                  <Select>
                    <SelectTrigger className="w-32">
                      <SelectValue placeholder="Experience" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="internship">Internship</SelectItem>
                      <SelectItem value="newly-grad">Newly Grad</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="flex justify-center">
                <JobSearchInfoCard />
              </div>
              <div className="grid gap-6 md:gap-8">
                {
                  isFetching && !isFetchingNextPage ? (
                    renderSkeleton()
                  ) : (
                    <>
                      {data?.pages.map((group, i) => (
                        <React.Fragment key={i}>
                          {group.jobs.map((job: Job, index: number) => (
                            <Card key={index}>
                              <CardHeader className="flex flex-row items-center gap-4">
                                {job.employer_logo && (
                                  <Avatar>
                                    <AvatarImage src={job.employer_logo.toString()} alt={job.employer_name?.toString()} />
                                  </Avatar>
                                ) || (
                                    <BriefcaseIcon className="h-6 w-6" />
                                  )}
                                <div className="grid gap-1">
                                  <CardTitle>{job.job_title}</CardTitle>
                                  <CardDescription>
                                    <HoverCard>
                                      <HoverCardTrigger asChild>
                                        <span className="underline">{job.employer_name}</span>
                                      </HoverCardTrigger>
                                      <HoverCardContent className="w-80">
                                        <div className="flex justify-between space-x-4">
                                          <Avatar>
                                            <AvatarImage src={job.employer_logo?.toString()} alt={job.employer_name?.toString()} />
                                            <AvatarFallback>{(job.employer_name as string)?.charAt(0)}</AvatarFallback>
                                          </Avatar>
                                          <div className="space-y-1">
                                            <h4 className="text-sm font-semibold">{job.employer_name}</h4>
                                            <p className="text-sm">
                                              {job.job_city}, {job.job_state}
                                            </p>
                                            <Link className="text-sm underline text-blue-500" href="#">
                                              Visit Website
                                            </Link>
                                          </div>
                                        </div>
                                      </HoverCardContent>
                                    </HoverCard>
                                    , {job.job_city}, {job.job_state}{"\n                                          "}
                                  </CardDescription>
                                </div>
                                <div className="ml-auto flex flex-col items-end">
                                  <div className="text-sm text-gray-500 dark:text-gray-400">
                                    Last Updated on: {job.updatedAt ? new Date(job.updatedAt).toLocaleDateString() : 'N/A'}
                                  </div>
                                  <div className="text-sm text-gray-500 dark:text-gray-400">
                                    Apply by: {job.job_offer_expiration_datetime_utc ? new Date(job.job_offer_expiration_datetime_utc).toLocaleDateString() : 'N/A'}
                                  </div>
                                  <Bookmark jobId={job.job_id} />
                                </div>
                              </CardHeader>
                              <CardContent className="grid gap-2">
                                <TruncatedText text={job.job_description ?? ''} maxLength={100} />
                                <div className="grid gap-2">
                                  <div className="text-sm text-gray-500 dark:text-gray-400">
                                    <strong>Estimated Salary:</strong>
                                    {job.job_min_salary && job.job_max_salary ? (
                                      ` $${new Intl.NumberFormat().format(job.job_min_salary)} - $${new Intl.NumberFormat().format(job.job_max_salary)}`
                                    ) : job.job_min_salary ? (
                                      ` From $${new Intl.NumberFormat().format(job.job_min_salary)}`
                                    ) : job.job_max_salary ? (
                                      ` Up to $${new Intl.NumberFormat().format(job.job_max_salary)}`
                                    ) : " Salary not disclosed"}
                                  </div>
                                  <div className="text-sm text-gray-500 dark:text-gray-400">
                                    <strong>Experience: </strong>
                                    {job.job_required_experience ? renderExperience(job.job_required_experience as { no_experience_required: boolean; experience_mentioned: boolean; experience_preferred: boolean; required_experience_in_months: number; }) : 'Not Specified'}
                                  </div>
                                  <div className="text-sm text-gray-500 dark:text-gray-400">
                                    <strong>Qualifications: </strong>
                                    {Array.isArray(job.job_required_skills) ? job.job_required_skills.join(', ') : 'N/A'}{"\n                                          "}
                                  </div>
                                  <div className="text-sm text-gray-500 dark:text-gray-400">
                                    <strong>Benefits: </strong>
                                    {Array.isArray(job.job_benefits) ?
                                      job.job_benefits.map(benefit =>
                                        typeof benefit === 'string' ?
                                          benefit.split('_').map(word =>
                                            word.charAt(0).toUpperCase() + word.slice(1)
                                          ).join(' ') :
                                          ''
                                      ).filter(Boolean).join(', ') :
                                      'N/A'
                                    }
                                    {"\n                                          "}
                                  </div>
                                </div>
                                <Link
                                  className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                                  href={job.job_apply_link}
                                >
                                  View Details
                                </Link>
                              </CardContent>
                            </Card>
                          ))}
                        </React.Fragment>
                      ))}
                      {isFetchingNextPage && renderSkeleton()}
                    </>
                  )}
                <div ref={loadMoreRef} className="mb-8"></div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

function renderExperience(expData = { no_experience_required: false, experience_mentioned: false, experience_preferred: false, required_experience_in_months: 0 }) {
  // Convert experience from months to years
  let experienceYears = expData.required_experience_in_months / 12;
  let experienceDisplay = '';

  if (expData.no_experience_required) {
    experienceDisplay = 'No Experience Required';
  } else if (expData.experience_mentioned && expData.required_experience_in_months != null) {
    // Check if the experience converts neatly into whole years
    if (Number.isInteger(experienceYears)) {
      experienceDisplay = `${experienceYears} year(s)`;
    } else {
      // If not, display as a decimal to one place
      experienceDisplay = `${experienceYears.toFixed(1)} year(s)`;
    }

    // Add a note if experience is preferred but not strictly required
    if (expData.experience_preferred) {
      experienceDisplay += ' (Experience Preferred)';
    }
  } else {
    experienceDisplay = 'Experience Not Specified';
  }

  return experienceDisplay;
}


function BriefcaseIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="14" x="2" y="7" rx="2" ry="2" />
      <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
    </svg>
  )
}

function GithubIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      role="img"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
    >
      <title>GitHub</title>
      <path
        fill="currentColor"
        d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.775.418-1.305.762-1.605-2.665-.3-5.467-1.332-5.467-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"
      />
    </svg>
  );
}


function ExternalLinkIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
      <polyline points="15 3 21 3 21 9" />
      <line x1="10" x2="21" y1="14" y2="3" />
    </svg>
  )
}