/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Ixydi5jz06w
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { HoverCardTrigger, HoverCardContent, HoverCard } from "@/components/ui/hover-card"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { JSX, SVGProps } from "react"

export function JobBoard() {
  return (
    <div className="flex flex-col min-h-screen bg-white dark:bg-gray-900">
      <header className="flex items-center h-16 px-4 border-b dark:border-gray-800 md:px-6">
        <Link href="#">
          <img
            alt="Yeshiva University Logo"
            className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
            height="70"
            src="/placeholder.svg"
            width="140"
          />
          <span className="sr-only">Yeshiva University</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Home
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            About
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 md:gap-8">
              <div className="flex flex-col md:flex-row items-start md:items-center gap-4 md:gap-8">
                <div className="grid gap-1">
                  <h1 className="text-2xl font-bold tracking-tight">Job Listings</h1>
                  <p className="text-gray-500 dark:text-gray-400">
                    Explore the latest job postings from top tech companies.
                  </p>
                </div>
                <div className="flex gap-4 md:gap-6 md:ml-auto">
                  <Input className="w-full md:w-64" placeholder="Search jobs..." type="search" />
                  <Select>
                    <SelectTrigger className="w-32">
                      <SelectValue placeholder="Location" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="mountain-view">New York</SelectItem>
                      <SelectItem value="cupertino">New Jersey</SelectItem>
                    </SelectContent>
                  </Select>
                  <Select>
                    <SelectTrigger className="w-32">
                      <SelectValue placeholder="Experience" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="internship">Internship</SelectItem>
                      <SelectItem value="newly-grad">Newly Grad</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="grid gap-6 md:gap-8">
                <Card>
                  <CardHeader className="flex flex-row items-center gap-4">
                    <BriefcaseIcon className="h-6 w-6" />
                    <div className="grid gap-1">
                      <CardTitle>Software Engineer</CardTitle>
                      <CardDescription>
                        <HoverCard>
                          <HoverCardTrigger asChild>
                            <span className="underline">Google</span>
                          </HoverCardTrigger>
                          <HoverCardContent className="w-80">
                            <div className="flex justify-between space-x-4">
                              <Avatar>
                                <AvatarImage src="/placeholder-avatar.jpg" />
                                <AvatarFallback>G</AvatarFallback>
                              </Avatar>
                              <div className="space-y-1">
                                <h4 className="text-sm font-semibold">Google</h4>
                                <p className="text-sm">
                                  Google LLC is an American multinational technology company that specializes in
                                  Internet-related services and products.
                                </p>
                                <Link className="text-sm underline text-blue-500" href="#">
                                  <ExternalLinkIcon className="mr-1 h-4 w-4" />
                                  Visit Website
                                </Link>
                              </div>
                            </div>
                          </HoverCardContent>
                        </HoverCard>
                        , Mountain View, CA{"\n                                          "}
                      </CardDescription>
                    </div>
                    <div className="ml-auto text-sm text-gray-500 dark:text-gray-400">Apply by: Dec 31, 2024</div>
                  </CardHeader>
                  <CardContent className="grid gap-2">
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      We are looking for a skilled software engineer to join our team.
                    </p>
                    <div className="grid gap-2">
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        <strong>Estimated Salary:</strong>
                        $80,000 - $120,000{"\n                                          "}
                      </div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        <strong>Start Date:</strong>
                        Immediate{"\n                                          "}
                      </div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        <strong>Experience:</strong>
                        2+ years{"\n                                          "}
                      </div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        <strong>Qualifications:</strong>
                        Python{"\n                                          "}
                      </div>
                    </div>
                    <Link
                      className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                      href="#"
                    >
                      View Details
                    </Link>
                  </CardContent>
                </Card>
                <Card>
                  <CardHeader className="flex flex-row items-center gap-4">
                    <BriefcaseIcon className="h-6 w-6" />
                    <div className="grid gap-1">
                      <CardTitle>Data Scientist</CardTitle>
                      <CardDescription>
                        <HoverCard>
                          <HoverCardTrigger asChild>
                            <span className="underline">Apple</span>
                          </HoverCardTrigger>
                          <HoverCardContent className="w-80">
                            <div className="flex justify-between space-x-4">
                              <Avatar>
                                <AvatarImage src="/placeholder-avatar.jpg" />
                                <AvatarFallback>A</AvatarFallback>
                              </Avatar>
                              <div className="space-y-1">
                                <h4 className="text-sm font-semibold">Apple</h4>
                                <p className="text-sm">
                                  Apple Inc. is an American multinational technology company that specializes in
                                  consumer electronics, computer software, and online services.
                                </p>
                                <Link className="text-sm underline text-blue-500" href="#">
                                  <ExternalLinkIcon className="mr-1 h-4 w-4" />
                                  Visit Website
                                </Link>
                              </div>
                            </div>
                          </HoverCardContent>
                        </HoverCard>
                        , Cupertino, CA{"\n                                          "}
                      </CardDescription>
                    </div>
                    <div className="ml-auto text-sm text-gray-500 dark:text-gray-400">Apply by: Jan 15, 2025</div>
                  </CardHeader>
                  <CardContent className="grid gap-2">
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      We are seeking a talented data scientist to join our team.
                    </p>
                    <div className="grid gap-2">
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        <strong>Estimated Salary:</strong>
                        $100,000 - $140,000{"\n                                          "}
                      </div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        <strong>Start Date:</strong>
                        Immediate{"\n                                          "}
                      </div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        <strong>Experience:</strong>
                        3+ years{"\n                                          "}
                      </div>
                    </div>
                    <Link
                      className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                      href="#"
                    >
                      View Details
                    </Link>
                  </CardContent>
                </Card>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

function BriefcaseIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="14" x="2" y="7" rx="2" ry="2" />
      <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
    </svg>
  )
}


function ExternalLinkIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
      <polyline points="15 3 21 3 21 9" />
      <line x1="10" x2="21" y1="14" y2="3" />
    </svg>
  )
}
